experiment:
  description: regression w/ FGEL
  output_location: results/dsprites_nonlinear/
  load: null
  resume: false

data:
  data_key: dsprites-nonlinear

  train: data/dsprites-dataset/dsprites_train.npz
  val: data/dsprites-dataset/dsprites_val.npz
  val_ood: data/dsprites-dataset/dsprites_val.npz
  test: data/dsprites-dataset/dsprites_test.npz
  test_ood: data/dsprites-dataset/dsprites_test.npz
  target: position_y
  distractor: position_x
  nl_type: tricky
  noise: 2

  batch_size: 1024
  num_workers: 16

model:
  model_key: regressor
  trainer_key: fgel
  modes:
    - train
    - val
    - val_ood
    - test
    - test_ood
  epochs: &num_epochs 200
  patience: 25

  trainer_config:
    reg_param: 1.0
    theta_reg_param: 0
    dual_func_network_kwargs:
      layer_widths:
        - 50
        - 20
      activation: LeakyReLU
      normalized: False
    theta_optim_args:
      optimizer:
        AdamW:
          lr: 0.0001
          weight_decay: 0.0001
      scheduler:
        CosineAnnealingLR:
          T_max: *num_epochs
    dual_optim_args:
      optimizer:
        OAdam:
          lr: 0.0001
          betas:
            - 0.5
            - 0.9
      scheduler:
        CosineAnnealingLR:
          T_max: *num_epochs

    # Fixed arguments
    default: False
    gpu: True
    gradient_descent_ascent: True
    pretrain: False
    pretrain_dual: False
    progress_bar: True

    # Following arguments are unused as batching/training is done in the wrapper class
    max_num_epochs: False
    batch_size: False
    eval_freq: False
    max_no_improve: False
    burn_in_cycles: False
    early_stopping: False

    # Unused arguments
    divergence: chi2
    reg_param_rkhs_norm: 0.0
    val_loss_func: hsic


  network:
    featurizer:
      - Conv2d:
          in_channels: 1
          out_channels: 16
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - Conv2d:
          in_channels: 16
          out_channels: 32
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - MaxPool2d:
          kernel_size: 2
          stride: 2
      - Conv2d:
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - MaxPool2d:
          kernel_size: 2
          stride: 2

    fc1:
      - Linear:
          in_features: 256
          out_features: 128
      - LeakyReLU:
          inplace: True

    fc2:
      - Linear:
          in_features: 128
          out_features: 64

    target:
      - Linear:
          in_features: 64
          out_features: 1
