experiment:
  description: regression w/ VMM
  output_location: results/dsprites_linear/
  load: null
  resume: false

data:
  data_key: dsprites

  train: data/dsprites-dataset/dsprites_train.npz
  val: data/dsprites-dataset/dsprites_val.npz
  val_ood: data/dsprites-dataset/dsprites_val.npz
  test: data/dsprites-dataset/dsprites_test.npz
  test_ood: data/dsprites-dataset/dsprites_test.npz
  target: position_y
  distractor: position_x
  noise: 2
  regress: False

  batch_size: 1024
  num_workers: 4

model:
  model_key: regressor
  trainer_key: vmm

  trainer_config:
    default: False
    divergence: chi2
    reg_param: 0.01
    reg_param_rkhs_norm: 0.0
    dual_func_network_kwargs:
      layer_widths:
        - 50
        - 20
      activation: LeakyReLU
      normalized: True
    pretrain: False
    pretrain_dual: False
    early_stopping: False
    val_loss_func: hsic
    gpu: True

    theta_optim_args:
      optimizer:
        OAdam:
          lr: 0.0005
          betas:
            - 0.5
            - 0.9
      scheduler: False
    dual_optim_args:
      optimizer:
        OAdam:
          lr: 0.0001
          betas:
            - 0.5
            - 0.9
      scheduler: False
    gradient_descent_ascent: True
    max_num_epochs: 200
    batch_size: 1024
    eval_freq: 100
    max_no_improve: 500
    burn_in_cycles: 10

  modes:
    - train
    - val
    - val_ood
    - test
    - test_ood
  epochs: 200
  patience: 25

  network:
    featurizer:
      - Conv2d:
          in_channels: 1
          out_channels: 16
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - Conv2d:
          in_channels: 16
          out_channels: 32
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - MaxPool2d:
          kernel_size: 2
          stride: 2
      - Conv2d:
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
          padding: 1
      - LeakyReLU:
          inplace: True
      - MaxPool2d:
          kernel_size: 2
          stride: 2

    fc1:
      - Linear:
          in_features: 256
          out_features: 128
      - LeakyReLU:
          inplace: True

    fc2:
      - Linear:
          in_features: 128
          out_features: 64

    target:
      - Linear:
          in_features: 64
          out_features: 1

#  optimizer:
#    AdamW:
#      lr: 0.0001
#      weight_decay: 0.01
#
#  scheduler:
#    CosineAnnealingLR:
#      T_max: 200
